import { z } from "zod";

/**
 * ASK ICOS — frontend boundary for the Cognitive Runtime (lane C).
 *
 * The browser holds the owner's text and renders what the runtime streams
 * back. It never interprets intent, picks actions, approves anything or
 * produces an answer itself. Until the runtime exposes the endpoints below,
 * every turn ends NOT_CONNECTED. Proposed contract (BR-28):
 *
 *   POST /api/ask/turns  { turnId, conversationId?, text } → SSE of AskEvent
 *        `turnId` is generated by the client and is the idempotency key: a re-POST
 *        of the same turnId must replay that turn from seq 0, never start a second one.
 *   GET  /api/ask/turns/:turnId/events?afterSeq=N → SSE resume (SSE id = seq)
 *   POST /api/ask/turns/:turnId/cancel     stop and discard the turn
 *   POST /api/ask/turns/:turnId/interrupt  stop generating, keep what was said
 *
 * Stream rules: seq starts at 0 with `turn.started` and increases by exactly 1;
 * after a terminal event (completed / interrupted / cancelled / error) nothing follows.
 */
export const ASK_MAX_LENGTH = 2000;

const base = { turnId: z.string().min(1), seq: z.number().int().nonnegative() };

export const askEventSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("turn.started"), conversationId: z.string().min(1), ...base }),
  z.object({ type: z.literal("text.delta"), text: z.string(), ...base }),
  z.object({
    type: z.literal("tool.call"),
    toolCallId: z.string(),
    name: z.string(),
    status: z.enum(["started", "succeeded", "failed"]),
    summary: z.string().optional(),
    ...base,
  }),
  z.object({
    type: z.literal("mission.created"),
    missionId: z.string(),
    title: z.string(),
    ...base,
  }),
  /** The runtime asks; the decision goes through the governed approval path, not this chat. */
  z.object({
    type: z.literal("approval.requested"),
    approvalId: z.string(),
    summary: z.string(),
    risk: z.enum(["LOW", "MEDIUM", "HIGH", "CRITICAL"]),
    ...base,
  }),
  z.object({
    type: z.literal("context.used"),
    memory: z.array(z.object({ id: z.string(), label: z.string() })),
    contextTokens: z.number().int().nonnegative().optional(),
    ...base,
  }),
  z.object({ type: z.literal("turn.completed"), ...base }),
  z.object({ type: z.literal("turn.interrupted"), ...base }),
  z.object({ type: z.literal("turn.cancelled"), ...base }),
  z.object({
    type: z.literal("error"),
    code: z.string(),
    message: z.string(),
    retryable: z.boolean(),
    ...base,
  }),
]);
export type AskEvent = z.infer<typeof askEventSchema>;

const TERMINAL_EVENTS = new Set<AskEvent["type"]>([
  "turn.completed",
  "turn.interrupted",
  "turn.cancelled",
  "error",
]);
export const isTerminalEvent = (e: AskEvent) => TERMINAL_EVENTS.has(e.type);

/** Rendering caps: a runaway stream must not hang the tab. */
export const MAX_ANSWER_CHARS = 200_000;
export const MAX_FRAME_BUFFER = 1_000_000;

export type AskStatus =
  | "idle"
  | "sending"
  | "streaming"
  | "completed"
  | "interrupted"
  | "cancelled"
  | "error"
  | "reconnecting"
  | "not_connected";

const TERMINAL_STATUS = new Set<AskStatus>(["completed", "interrupted", "cancelled"]);
/** Finished, or failed until an explicit resume (`reconnecting`) re-opens it: later frames are ignored. */
const isClosed = (s: AskState) => TERMINAL_STATUS.has(s.status) || s.status === "error";

export interface AskState {
  status: AskStatus;
  conversationId: string | null;
  /** Client-generated at send: resume and cancel work even before `turn.started`. */
  turnId: string | null;
  /** Highest seq applied: resume asks for events after it; replays below it are ignored. */
  lastSeq: number;
  text: string;
  tools: {
    id: string;
    name: string;
    status: "started" | "succeeded" | "failed";
    summary?: string;
  }[];
  missions: { id: string; title: string }[];
  approvals: { id: string; summary: string; risk: string }[];
  context: { memory: { id: string; label: string }[]; contextTokens?: number } | null;
  error: { code: string; message: string; retryable: boolean } | null;
}

export const initialAsk = (conversationId: string | null = null): AskState => ({
  status: "idle",
  conversationId,
  turnId: null,
  lastSeq: -1,
  text: "",
  tools: [],
  missions: [],
  approvals: [],
  context: null,
  error: null,
});

export type AskAction =
  | { type: "send"; turnId: string }
  | { type: "event"; event: AskEvent }
  | { type: "not_connected" }
  | { type: "link_lost" }
  | { type: "turn_unknown" }
  | { type: "reconnecting" };

const lost = (state: AskState, code: string, message: string): AskState => ({
  ...state,
  status: "error",
  error: { code, message, retryable: true },
});

export function askReducer(state: AskState, action: AskAction): AskState {
  switch (action.type) {
    case "send":
      return { ...initialAsk(state.conversationId), status: "sending", turnId: action.turnId };
    case "not_connected":
      return { ...state, status: "not_connected" };
    case "reconnecting":
      return { ...state, status: "reconnecting", error: null };
    case "link_lost":
      // What arrived stays on screen; the turn outcome is unknown until resumed.
      return isClosed(state)
        ? state
        : lost(state, "LINK_LOST", "Connection to ICOS lost mid-turn.");
    case "turn_unknown":
      return {
        ...state,
        status: "error",
        error: {
          code: "TURN_UNKNOWN",
          message: "ICOS has no record of this turn.",
          retryable: false,
        },
      };
    case "event":
      return applyEvent(state, action.event);
  }
}

function applyEvent(state: AskState, e: AskEvent): AskState {
  // Strict isolation: only the turn this client started, and nothing after it ended.
  if (state.turnId === null || e.turnId !== state.turnId) return state;
  if (isClosed(state)) return state;
  if (e.seq <= state.lastSeq) return state; // replay after resume
  if (e.seq !== state.lastSeq + 1)
    return lost(
      state,
      "SEQ_GAP",
      `Missed events ${state.lastSeq + 1}..${e.seq - 1}; resume needed.`,
    );
  const s = { ...state, lastSeq: e.seq, error: null };
  switch (e.type) {
    case "turn.started":
      return { ...s, status: "streaming", conversationId: e.conversationId };
    case "text.delta":
      return s.text.length + e.text.length > MAX_ANSWER_CHARS
        ? {
            ...s,
            status: "error",
            error: {
              code: "ANSWER_TOO_LONG",
              message: "Answer exceeded the display cap.",
              retryable: false,
            },
          }
        : { ...s, status: "streaming", text: s.text + e.text };
    case "tool.call": {
      const tools = s.tools.filter((t) => t.id !== e.toolCallId);
      return {
        ...s,
        tools: [...tools, { id: e.toolCallId, name: e.name, status: e.status, summary: e.summary }],
      };
    }
    case "mission.created":
      return { ...s, missions: [...s.missions, { id: e.missionId, title: e.title }] };
    case "approval.requested":
      return {
        ...s,
        approvals: [...s.approvals, { id: e.approvalId, summary: e.summary, risk: e.risk }],
      };
    case "context.used":
      return { ...s, context: { memory: e.memory, contextTokens: e.contextTokens } };
    case "turn.completed":
      return { ...s, status: "completed" };
    case "turn.interrupted":
      return { ...s, status: "interrupted" };
    case "turn.cancelled":
      return { ...s, status: "cancelled" };
    case "error":
      return {
        ...s,
        status: "error",
        error: { code: e.code, message: e.message, retryable: e.retryable },
      };
  }
}

// ------------------------------------------------------------------ transport

/** `not_found` = the runtime answered but does not know this turn (resume/cancel). */
export type StreamOutcome = "ended" | "not_connected" | "not_found" | "link_lost";
export type ControlOutcome = "ok" | "not_connected" | "not_found" | "failed";

export interface AskTransport {
  start(
    input: { turnId: string; conversationId: string | null; text: string },
    onEvent: (e: AskEvent) => void,
    signal?: AbortSignal,
  ): Promise<StreamOutcome>;
  resume(
    turnId: string,
    afterSeq: number,
    onEvent: (e: AskEvent) => void,
    signal?: AbortSignal,
  ): Promise<StreamOutcome>;
  cancel(turnId: string): Promise<ControlOutcome>;
  interrupt(turnId: string): Promise<ControlOutcome>;
}

/** Parses an SSE body; each `data:` block must be a valid AskEvent or it is dropped. */
export async function readEventStream(
  body: ReadableStream<Uint8Array>,
  onEvent: (e: AskEvent) => void,
): Promise<void> {
  const reader = body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  for (;;) {
    const { value, done } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true }).replaceAll("\r\n", "\n");
    if (buffer.length > MAX_FRAME_BUFFER) {
      await reader.cancel();
      throw new Error("SSE_FRAME_TOO_LARGE");
    }
    let cut: number;
    while ((cut = buffer.indexOf("\n\n")) >= 0) {
      const block = buffer.slice(0, cut);
      buffer = buffer.slice(cut + 2);
      const data = block
        .split("\n")
        .filter((l) => l.startsWith("data:"))
        .map((l) => l.slice(5).trimStart())
        .join("\n");
      if (!data) continue;
      try {
        const parsed = askEventSchema.safeParse(JSON.parse(data));
        if (parsed.success) onEvent(parsed.data);
      } catch {
        // malformed frame: ignored, never rendered
      }
    }
  }
}

/** A 404 carrying the ICOS error envelope is the runtime speaking, not a missing route. */
async function isFrameworkNotFound(res: Response): Promise<boolean> {
  if (res.status !== 404) return false;
  try {
    const body = (await res.clone().json()) as { error?: { code?: unknown } };
    return typeof body?.error?.code !== "string";
  } catch {
    return true;
  }
}

export function httpAskTransport(doFetch: typeof fetch = fetch): AskTransport {
  const stream = async (
    res: Response,
    onEvent: (e: AskEvent) => void,
    missingRouteMeans: "not_connected" | "not_found",
  ): Promise<StreamOutcome> => {
    if (res.status === 404)
      return (await isFrameworkNotFound(res)) ? missingRouteMeans : "not_found";
    if (!res.ok || !res.body || !res.headers.get("content-type")?.includes("text/event-stream"))
      return "link_lost";
    try {
      await readEventStream(res.body, onEvent);
      return "ended";
    } catch {
      return "link_lost";
    }
  };
  const post = async (path: string, body?: unknown, signal?: AbortSignal) =>
    doFetch(path, {
      method: "POST",
      credentials: "same-origin",
      headers: { "content-type": "application/json", accept: "text/event-stream" },
      body: body === undefined ? undefined : JSON.stringify(body),
      signal,
    });
  const control = async (path: string): Promise<ControlOutcome> => {
    try {
      const res = await post(path);
      if (res.status === 404)
        return (await isFrameworkNotFound(res)) ? "not_connected" : "not_found";
      return res.ok ? "ok" : "failed";
    } catch {
      return "failed";
    }
  };
  const turnPath = (turnId: string) => `/api/ask/turns/${encodeURIComponent(turnId)}`;
  return {
    async start(input, onEvent, signal) {
      try {
        return await stream(await post("/api/ask/turns", input, signal), onEvent, "not_connected");
      } catch {
        return "link_lost";
      }
    },
    async resume(turnId, afterSeq, onEvent, signal) {
      try {
        const res = await doFetch(`${turnPath(turnId)}/events?afterSeq=${afterSeq}`, {
          credentials: "same-origin",
          headers: { accept: "text/event-stream" },
          signal,
        });
        return await stream(res, onEvent, "not_connected");
      } catch {
        return "link_lost";
      }
    },
    cancel: (turnId) => control(`${turnPath(turnId)}/cancel`),
    interrupt: (turnId) => control(`${turnPath(turnId)}/interrupt`),
  };
}

export const ASK_EXAMPLES = [
  "Pourquoi CORE3 est bloqué ?",
  "Quels providers sont dégradés ?",
  "Quelle amélioration d'ICOS apporte le plus d'autonomie pour le moins de risque ?",
];
