import type { Task } from "@/core/contracts";

export const demoTasks = [
  {
    id: "task-001",
    title: "Diagnostic du socle ICOS",
    missionId: "mission-001",
    goalId: "goal-001",
    planId: "plan-001",
    objective: "Validate ICOS core foundations",
    instructions: "Run diagnostic checks on core services",
    dependencies: [],
    successCriteria: ["All checks pass", "No critical errors"],
    requiredCapabilities: ["diagnostic", "analysis"],
    riskClass: "reversible",
    allowedFileScope: ["src/", "scripts/"],
    expectedArtifacts: ["diagnostic-report.json"],
    priority: 3,
    attemptBudget: 3,
    reviewPolicy: "if_risky",
    integrationPolicy: "",
    assignedAgentId: "agent-cto",
    status: "succeeded",
    actionIds: [],
    createdAt: "2026-07-20T09:00:00.000Z",
    updatedAt: "2026-07-20T17:30:00.000Z",
  },
  {
    id: "task-002",
    title: "Politique d’approbation",
    missionId: "mission-001",
    goalId: "goal-001",
    planId: "plan-001",
    objective: "Define approval policy for missions",
    instructions: "Draft and review approval workflow",
    dependencies: [],
    successCriteria: ["Policy documented", "Approved by governance"],
    requiredCapabilities: ["policy-writing", "review"],
    riskClass: "read_only",
    allowedFileScope: ["docs/", "policies/"],
    expectedArtifacts: ["approval-policy.md"],
    priority: 2,
    attemptBudget: 2,
    reviewPolicy: "always",
    integrationPolicy: "",
    assignedAgentId: "agent-quality",
    status: "awaiting_approval",
    actionIds: ["action-001", "action-003"],
    createdAt: "2026-07-21T08:00:00.000Z",
    updatedAt: "2026-07-21T08:15:00.000Z",
  },
  {
    id: "task-003",
    title: "Cartographie des intégrations",
    missionId: "mission-001",
    goalId: "goal-001",
    planId: "plan-001",
    objective: "Map external integrations",
    instructions: "Identify and document integration points",
    dependencies: [],
    successCriteria: ["Integration map completed", "All endpoints listed"],
    requiredCapabilities: ["integration", "documentation"],
    riskClass: "sensitive",
    allowedFileScope: ["integrations/", "src/services/*"],
    expectedArtifacts: ["integration-map.yaml"],
    priority: 4,
    attemptBudget: 2,
    reviewPolicy: "always",
    integrationPolicy: "",
    assignedAgentId: "agent-infra",
    status: "queued",
    actionIds: ["action-002"],
    createdAt: "2026-07-21T08:05:00.000Z",
    updatedAt: "2026-07-21T08:05:00.000Z",
  },
] satisfies readonly Task[];