import type { Agent } from "./types";

export const demoAgents = [
  {
    id: "agent-ceo",
    name: "CEO",
    role: "Direction générale",
    status: "standby",
    authorizationLevel: 3,
    description: "Arbitre les priorités et prépare les décisions stratégiques.",
  },
  {
    id: "agent-cto",
    name: "CTO",
    role: "Direction technique",
    status: "available",
    authorizationLevel: 2,
    description: "Cadre l’architecture, la sécurité et la qualité technique.",
  },
  {
    id: "agent-art",
    name: "Direction artistique",
    role: "Identité et création",
    status: "available",
    authorizationLevel: 1,
    description: "Maintient la cohérence visuelle et les standards créatifs.",
  },
  {
    id: "agent-webdesign",
    name: "Webdesign",
    role: "Expérience utilisateur",
    status: "standby",
    authorizationLevel: 1,
    description: "Conçoit les interfaces et leurs parcours opérationnels.",
  },
  {
    id: "agent-development",
    name: "Développement",
    role: "Production logicielle",
    status: "available",
    authorizationLevel: 2,
    description: "Prépare des changements de code vérifiables et réversibles.",
  },
  {
    id: "agent-seo",
    name: "SEO",
    role: "Visibilité organique",
    status: "offline",
    authorizationLevel: 1,
    description: "Analyse la présence éditoriale et les opportunités de recherche.",
  },
  {
    id: "agent-sales",
    name: "Commercial",
    role: "Développement commercial",
    status: "standby",
    authorizationLevel: 1,
    description: "Structure les opportunités et prépare le suivi commercial.",
  },
  {
    id: "agent-crm",
    name: "CRM",
    role: "Relation client",
    status: "offline",
    authorizationLevel: 1,
    description: "Organise le contexte client sans effectuer de contact autonome.",
  },
  {
    id: "agent-infra",
    name: "Infrastructure",
    role: "Systèmes et déploiement",
    status: "standby",
    authorizationLevel: 2,
    description: "Supervise la disponibilité et prépare les opérations sensibles.",
  },
  {
    id: "agent-quality",
    name: "Contrôle qualité",
    role: "Validation et conformité",
    status: "available",
    authorizationLevel: 2,
    description: "Vérifie les livrables, les preuves et le respect des garde-fous.",
  },
] satisfies readonly Agent[];
